from enum import Enum

class TokenType(Enum):
    AND ="and"
    CLASS = "class"
    ALSO = "also"
    FALSE = "false"
    FOR = "for"
    FUN = "fun"
    IF = "if"
    NULL = "null"
    OR = "or"
    PRINT = "print"
    RETURN = "return"
    SUPER = "super"
    THIS = "this"
    TRUE = "true"
    WHILE = "while"
    OPENPARENT = "("
    CLOSEPARENT = ")"
    OPENBRACKET = "{"
    CLOSEBRACKET = "}"
    COMMA = ","
    DOT = "."
    DOTCOMMA = ";"
    SUB = "-"
    ADD = "+"
    MULT = "*"
    DIVID = "/"
    NEGATION = "!"
    DIFFERENT = "!="
    ASIGNATION = "="
    EQUAL = "=="
    LESS = "<"
    LESSEQUAL = "<="
    GREAT = ">"
    GREATEQUAL = ">="
    COMMENT = "#"
    MULTCOMMENT = "''''''"
    NUMBER = "NUM"
    IDENTIFIER = "ID"
    VAR = "var"
    EOF = "EOF" 
    #Identificador,
    #Cadena
    #Numero
    #Cada palabra reservada tiene su nombre de token